import yfinance as yf
import pandas as pd

# 1. Define your "Picks & Shovels" basket
tickers = ['QQQ', 'SOXX', 'NVDA', 'AVGO', 'MU', 'SNDK', 'MCHP', 'ASML']

# 2. Strategy Parameters (Change these to experiment!)
PULLBACK_PCT = 0.05    # Buy when stock drops 5% from its recent peak
PROFIT_TARGET = 0.12   # Sell when stock gains 12% from our buy price
LOOKBACK_DAYS = 20     # Look at the highest high of the last 20 trading days

print(f"--- Running Backtest (Parameters: {PULLBACK_PCT*100}% Dip / {PROFIT_TARGET*100}% Profit) --- \n")

for ticker in tickers:
    # Fetch 2 years of daily historical data
    df = yf.download(ticker, start='2024-07-01', end='2026-07-01', progress=False)
    
    if df.empty:
        print(f"No data found for {ticker}")
        continue
        
    # Flatten multi-index columns if generated by yfinance
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    in_position = False
    buy_price = 0
    trades_won = 0
    total_trades = 0
    
    # Calculate rolling maximum high to find local peaks
    df['Local_High'] = df['High'].rolling(window=LOOKBACK_DAYS).max()
    
    for i in range(LOOKBACK_DAYS, len(df)):
        current_close = float(df['Close'].iloc[i])
        current_high = float(df['High'].iloc[i])
        local_peak = float(df['Local_High'].iloc[i-1]) # Look at yesterday's peak
        
        if not in_position:
            # CHECK FOR BUY: Price dropped by PULLBACK_PCT from the local peak
            target_buy_zone = local_peak * (1 - PULLBACK_PCT)
            if current_close <= target_buy_zone:
                in_position = True
                buy_price = current_close
                total_trades += 1
        else:
            # CHECK FOR SELL: Price hit our profit target
            target_sell_price = buy_price * (1 + PROFIT_TARGET)
            if current_high >= target_sell_price:
                trades_won += 1
                in_position = False
                buy_price = 0

    # Print out how this specific stock did
    win_rate = (trades_won / total_trades * 100) if total_trades > 0 else 0
    status = "Still holding open trade" if in_position else "All positions closed"
    print(f"Ticker: {ticker:<5} | Total Trades Triggered: {total_trades:<3} | Targets Hit: {trades_won:<3} | Success Rate: {win_rate:.1f}% ({status})")

print("\n--- End of Experiment ---")